### ISSUE TITLE
advection_850.grib not found

### ISSUE THREAD

**Issue by ahmedshaaban1** [ecmwf/metview-docs#3]
All, 
Regarding to the example [link](https://metview.readthedocs.io/en/latest/gen_files/gallery/advection.html#gallery-advection). 
The data file "advection_850.grib" is not found among the data files [here](https://github.com/ecmwf/metview-docs/tree/master/docs/examples). 
Thanks 

_No response_

**Comment by iainrussell** [comment]
Hello @ahmedshaaban1,

Thanks for the report. In fact, many of these files do not reside in the repo, as we did not want to make the repo too large. Instead, they reside on a separate download server. The gallery example tries to read the file from local disk, and if it is not there, it will try to download from our server.

```
filename = "advection_850.grib"
if mv.exist(filename):
    f = mv.read(filename)
else:
    f = mv.gallery.load_dataset(filename)
```
If this does not work for you, you may be running a slightly older version of metview-python (pre-1.13.0), which tried to download from a server that has since been decommissioned. But if you use a newer version, it should download the file correctly.

Best regards,
Iain

**Comment by ahmedshaaban1** [comment]
Dear Iain, 
Thanks a lot for your response. Is a direct link (HTTP or FTP) available to download the data? 
Thanks

**Comment by iainrussell** [comment]
Dear @ahmedshaaban1,
Sure, this link gets you the data: https://get.ecmwf.int/repository/test-data/metview/gallery/advection_850.grib
Cheers,
Iain

**Comment by ahmedshaaban1** [comment]
Thanks a lot.
